server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

ribbon:
  eureka:
    enabled: true

# 设置feign客户端超时时间
ribbon:
  ReadTimeount: 5000   # 建立连接所用的时间，适用于网络正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000 # 建立连接后从服务器读取到可用资源所用的时间



logging:
  level:
  com.yh.cloud.service.PaymentFeignService: debug